### PR TITLE
Kafka: Use alpine base image, update to 0.10.2.0

### PR DESCRIPTION
**Pull request by fhemberger**
`openjdk:8-jre-alpine` already includes Scala 2.11.8

### CODE REVIEW

**Comment by solsson** [comment]
Great, that reduces layer size quite a bit. And I like the `--virtual build-dependencies` package concept.

**Comment by solsson** [comment]
I saw there were some more pushes coming in, so let me know when you think it's ready for merge.

**Comment by fhemberger** [comment]
@solsson That's all. ;)

**Comment by solsson** [comment]
I had some issues with Alpine's DNS client in Kubernetes, but that was a year ago almost ago and I think they have fixed it.

**Comment by fhemberger** [comment]
Oh, didn't know that and so I haven't tested that yet … I just got started setting up Kafka on Kubernetes and browsed your Dockerfile. Also I try to use Alpine wherever it is possible. ;)

**Comment by fhemberger** [comment]
Next step is automating topic creation through a ConfigMap. ;)

**Comment by solsson** [comment]
I'll merge and build in this repo, but keep an open discussion in https://github.com/solsson/kubernetes-kafka/pull/1. For production use there's more testing to do with 0.10.2.

**Comment by fhemberger** [comment]
You could also move back to `ENV kafka_version=0.10.1.1` and just merge the Alpine change.

**Comment by solsson** [comment]
The images from this repo are for testing anyway, so it's great to keep them up to date.

**Comment by solsson** [comment]
Built `solsson/kafka:0.10.2.0-alpine@sha256:a5256a1026750b5cad5a127dfe685f8b4b8053d06443392150c208ad84deaf48`

**Pull request merged**
