### PR TITLE
Use Java 11 everywhere

### PR DESCRIPTION
**Pull request by solsson**
Java 10 came with support for docker memory limits by default, see https://blog.docker.com/2018/04/improved-docker-container-integration-with-java-10/, but wasn't LTS. Kafka 2.1.0 supports Java 11.

### CODE REVIEW

**Comment by charlspjohn** [comment]
-XX:+UnlockExperimentalVMOptions
-XX:+UseCGroupMemoryLimitForHeap

These jvm options causing kafka-prometheus-jmx-exporter not to start http server. Can someone fix this ?

**Comment by solsson** [comment]
I think there was a Release note from Oracle somewhere saying that these flags have been deprecated. Or maybe it was in https://medium.com/adorsys/jvm-memory-settings-in-a-container-environment-64b0840e1d9e.

**Comment by solsson** [comment]
@charlspjohn If you need the hash for the old :latest it's here: https://github.com/Yolean/kubernetes-kafka/blob/v4.3.0/prometheus/50-kafka-jmx-exporter-patch.yml#L17

**Comment by charlspjohn** [comment]
> I think there was a Release note from Oracle somewhere saying that these flags have been deprecated. Or maybe it was in https://medium.com/adorsys/jvm-memory-settings-in-a-container-environment-64b0840e1d9e.

Can it be removed from dockerfile so that the public latest image will run without error ?

**Comment by solsson** [comment]
I don't see these flags in the Dockerfile. Or are you referring to some other Dockerfile? You can remove the flags from the statefulset resource (https://github.com/Yolean/kubernetes-kafka/blob/v4.3.1/prometheus/50-kafka-jmx-exporter-patch.yml#L20) which is already done in https://github.com/Yolean/kubernetes-kafka/blob/v5.0.3/prometheus/50-kafka-jmx-exporter-patch.yml.

**Comment by charlspjohn** [comment]
> I don't see these flags in the Dockerfile. Or are you referring to some other Dockerfile? You can remove the flags from the statefulset resource (https://github.com/Yolean/kubernetes-kafka/blob/v4.3.1/prometheus/50-kafka-jmx-exporter-patch.yml#L20) which is already done in https://github.com/Yolean/kubernetes-kafka/blob/v5.0.3/prometheus/50-kafka-jmx-exporter-patch.yml.

Got it thanks, I was using a local helm project and the options were there.

**Comment by solsson** [comment]
My recommendation is to always use sha256-tagged image URLs. You never know what kind of crap a maintainer like me might put into the next build :)

**Pull request merged**
