### PR TITLE
rename / update kafka-manager to cmak

### PR DESCRIPTION
**Pull request by spike83**

### CODE REVIEW

**Comment by solsson** [comment]
Thanks. Now that we're revisiting kafka-manager/cmak it might be worth to dig a bit deeper. Did you look for an official dockerfile? Are there attempts to do graalvm native-image builds in the cmak community?

**Comment by spike83** [comment]
Yes, thought about this as well but had to solve my issue with having a new version and the new naming stuff. I've seen your native initiative and like it very much!
I've not seen any docker image from the community but didn't invest in a deep search.
IMO this is already an improvement with java 11 and latest version so for me this image is fine for now.
Feel free to adjust as you wish.
If I find time I may push it to graalvm.

**Comment by solsson** [comment]
I took the liberty of changing to the JRE image for the runtime target, add cmak to the https://hub.docker.com/r/solsson/kafka autobuild and switching to nonroot user because there's no better time to do that than when image URLs change. I assumed that it doesn't need to write to any existing files during runtime, or that if it does so it'll use $HOME.

I noticed when testing that termination signals seem ineffective. The bin script is bash so I see no obvious reason why. I guess it doesn't matter much because CMAK doesn't persist anything. Let's wait for the autobuild and then do some actual kubernetes testing.

**Comment by solsson** [comment]
`solsson/kafka:cmak@sha256:03849b98935d6215e86cab940a53cbd37cded94ffeab5040d1dbf2b60e1ac7a6`

**Pull request merged**
